/* ============================================================
   首頁「本日精選 / Today's Brew」金句池
   ------------------------------------------------------------
   ‧ 中文(zh)與英文(en)是兩個獨立的池子,不是互相翻譯;
     語言切換時各自從自己的池子抽。
   ‧ 一行一句。格式:
       { "text": "金句內容" },
       { "text": "金句內容", "author": "作者" },
     沒有可查證出處的句子不掛 author(寧可不掛,也不掛錯)。
   ‧ 每一行結尾要有逗號,只有每個池子的最後一句不用。
     雙引號裡的內容如果本身有雙引號,要寫成 \"。
   ‧ 安全機制:這支檔案就算格式寫壞、載入失敗,首頁也不會壞——
     index.html 會自動退回內建的備用金句,並略過格式不對的單句。
   ============================================================ */
window.BREW_QUOTES = {
  zh: [
    { "text": "時間，是投資人最強的朋友。" },
    { "text": "與其猜最低點，不如早點開始。" },
    { "text": "市場永遠比你有耐心。" },
    { "text": "等待完美時機，往往錯過整個牛市。" },
    { "text": "投資最大的優勢，就是時間。" },
    { "text": "不要預測市場，讓市場替你工作。" },
    { "text": "真正的複利，不是利率，而是時間。" },
    { "text": "越想抄底，越容易踏空。" },
    { "text": "慢慢變有錢，比快速致富更可靠。" },
    { "text": "定期定額，不是為了買最低，而是避免買最高。" },
    { "text": "紀律，永遠比預測更有價值。" },
    { "text": "市場每天都在變，紀律不用。" },
    { "text": "你不需要猜明天，只需要投資今天。" },
    { "text": "真正的高手，不是猜對行情，而是從不缺席。" },
    { "text": "每一次投入，都是替未來買一點自由。" },
    { "text": "投資不是衝刺，是每個月都準時出現。" },
    { "text": "小額持續，勝過大額猶豫。" },
    { "text": "買得久，比買得巧更重要。" },
    { "text": "別人恐懼時，保持冷靜；別人瘋狂時，保持理性。" },
    { "text": "市場最大的敵人，不是下跌，而是情緒。" },
    { "text": "市場專門獎勵耐心，懲罰急躁。" },
    { "text": "價格每天都在變，價值不一定。" },
    { "text": "市場短期投票，長期稱重。" },
    { "text": "每一次泡沫，都有人相信這次不一樣。" },
    { "text": "市場不會因為你買了就停止下跌。" },
    { "text": "下跌不是風險，恐慌才是。" },
    { "text": "行情會反轉，人性不會。" },
    { "text": "最大的風險，是不知道自己在冒什麼風險。" },
    { "text": "投資不是追求最高報酬，而是避免致命錯誤。" },
    { "text": "先活下來，才有下一次機會。" },
    { "text": "別讓一次錯誤，毀掉十年的努力。" },
    { "text": "保住本金，比追求暴利更重要。" },
    { "text": "真正的高手，都很重視風險。" },
    { "text": "控制虧損，比放大利潤更容易。" },
    { "text": "市場不怕你犯錯，只怕你犯大錯。" },
    { "text": "現金也是一種部位。" },
    { "text": "投資不是比誰賺得快，而是比誰活得久。" },
    { "text": "有錢的人，不一定投資；會投資的人，通常越來越有錢。" },
    { "text": "真正的自由，是不用出售時間換收入。" },
    { "text": "每一筆投資，都是對未來自己的信任。" },
    { "text": "財富不是一天累積，而是每天累積。" },
    { "text": "今天的紀律，就是明天的財富。" },
    { "text": "不要讓今天的消費，偷走未來的自由。" },
    { "text": "錢會流向有耐心的人。" },
    { "text": "投資最大的報酬，不只是金錢，而是選擇權。" },
    { "text": "複利改變的，不只是資產，而是人生。" },
    { "text": "市場每天都有機會，但人生沒有那麼多次重新開始。" },
    { "text": "在別人貪婪時恐懼，在別人恐懼時貪婪。", "author": "華倫·巴菲特" },
    { "text": "價格是你付出的，價值是你得到的。", "author": "華倫·巴菲特" },
    { "text": "股市是把錢從沒耐性的人手中，轉移到有耐性的人手中的工具。", "author": "華倫·巴菲特" },
    { "text": "我們最喜歡的持有期限是永遠。", "author": "華倫·巴菲特" },
    { "text": "絕不投資你無法理解的事業。", "author": "華倫·巴菲特" },
    { "text": "你能做的最好投資，就是投資自己。", "author": "華倫·巴菲特" },
    { "text": "只有退潮時，你才會知道誰在裸泳。", "author": "華倫·巴菲特" },
    { "text": "分散投資，是對無知的保護。", "author": "華倫·巴菲特" },
    { "text": "危機時刻，現金加上勇氣，無價。", "author": "華倫·巴菲特" },
    { "text": "因預測回檔而虧掉的錢，遠比回檔本身虧掉的還多。", "author": "彼得·林區" },
    { "text": "知道你擁有什麼，也要知道為什麼擁有它。", "author": "彼得·林區" },
    { "text": "每個人都有賺錢的頭腦，但不是每個人都有足夠的膽識。", "author": "彼得·林區" },
    { "text": "每一檔股票背後都是一家公司，去了解它在做什麼。", "author": "彼得·林區" },
    { "text": "賺錢的關鍵，是不要被嚇得賣掉股票。", "author": "彼得·林區" },
    { "text": "投資人最大的問題，甚至是最大的敵人，往往是自己。", "author": "班傑明·葛拉漢" },
    { "text": "市場先生是來服務你的，不是來指導你的。", "author": "班傑明·葛拉漢" },
    { "text": "個別投資人應該始終以投資人自居，而不是投機者。", "author": "班傑明·葛拉漢" },
    { "text": "時間是你的朋友，衝動是你的敵人。", "author": "約翰·柏格" },
    { "text": "複利是世界第八大奇蹟。懂它的人，靠它賺錢；不懂的人，為它付錢。" },
    { "text": "查理和我一直都知道，我們終究會非常富有。但我們從不急著致富，因為我們知道那一天一定會來。", "author": "華倫·巴菲特" }
  ],
  en: [
    { "text": "Time in the market beats timing the market." },
    { "text": "Waiting for the perfect moment often means missing years of growth." },
    { "text": "Be fearful when others are greedy, and greedy when others are fearful.", "author": "Warren Buffett" },
    { "text": "Price is what you pay. Value is what you get.", "author": "Warren Buffett" },
    { "text": "The stock market is a device for transferring money from the impatient to the patient.", "author": "Warren Buffett" },
    { "text": "Our favorite holding period is forever.", "author": "Warren Buffett" },
    { "text": "Never invest in a business you cannot understand.", "author": "Warren Buffett" },
    { "text": "Risk comes from not knowing what you're doing.", "author": "Warren Buffett" },
    { "text": "The best investment you can make is in yourself.", "author": "Warren Buffett" },
    { "text": "Only when the tide goes out do you discover who's been swimming naked.", "author": "Warren Buffett" },
    { "text": "The four most dangerous words in investing are: \"This time it's different.\"", "author": "Sir John Templeton" },
    { "text": "Bull markets are born on pessimism, grow on skepticism, mature on optimism, and die on euphoria.", "author": "Sir John Templeton" },
    { "text": "The only investors who shouldn't diversify are those who are right 100% of the time.", "author": "Sir John Templeton" },
    { "text": "Far more money has been lost preparing for corrections than in the corrections themselves.", "author": "Peter Lynch" },
    { "text": "Know what you own, and know why you own it.", "author": "Peter Lynch" },
    { "text": "Everyone has the brainpower to make money in stocks. Not everyone has the stomach.", "author": "Peter Lynch" },
    { "text": "Behind every stock is a company. Find out what it's doing.", "author": "Peter Lynch" },
    { "text": "The key to making money is not getting scared out of them.", "author": "Peter Lynch" },
    { "text": "What is comfortable is rarely profitable.", "author": "Robert Arnott" },
    { "text": "Markets are never wrong. Opinions often are.", "author": "Jesse Livermore" },
    { "text": "There is nothing new on Wall Street.", "author": "Jesse Livermore" },
    { "text": "Diversification is protection against ignorance.", "author": "Warren Buffett" },
    { "text": "Cash combined with courage in a crisis is priceless.", "author": "Warren Buffett" },
    { "text": "The investor's chief problem—and even his worst enemy—is likely to be himself.", "author": "Benjamin Graham" },
    { "text": "Mr. Market is there to serve you, not to guide you.", "author": "Benjamin Graham" },
    { "text": "The individual investor should act consistently as an investor and not as a speculator.", "author": "Benjamin Graham" },
    { "text": "Invest for the long haul. Don't get too greedy and don't get too scared.", "author": "Shelby M. C. Davis" },
    { "text": "More money has been lost reaching for yield than at the point of a gun.", "author": "Ray DeVoe Jr." },
    { "text": "You make most of your money in a bear market—you just don't realize it at the time.", "author": "Shelby Cullom Davis" },
    { "text": "The biggest investing errors come not from factors that are informational or analytical, but from those that are psychological.", "author": "Howard Marks" },
    { "text": "You can't predict. You can prepare.", "author": "Howard Marks" },
    { "text": "Experience is what you got when you didn't get what you wanted.", "author": "Howard Marks" },
    { "text": "Volatility is not risk.", "author": "Howard Marks" },
    { "text": "The goal of the nonprofessional should not be to pick winners but to own all the winners.", "author": "John C. Bogle" },
    { "text": "Stay the course.", "author": "John C. Bogle" },
    { "text": "Don't look for the needle. Buy the haystack.", "author": "John C. Bogle" },
    { "text": "Costs matter.", "author": "John C. Bogle" },
    { "text": "The secret to investing is simple but not easy.", "author": "John C. Bogle" },
    { "text": "The market rewards discipline far more than brilliance." },
    { "text": "Investing isn't a sprint. It's a marathon." },
    { "text": "Get rich slowly, not quickly." },
    { "text": "Compound interest is the eighth wonder of the world. He who understands it, earns it; he who doesn't, pays it." },
    { "text": "Charlie and I always knew that we would become incredibly wealthy. But we were not in a hurry to get wealthy; we knew it would happen.", "author": "Warren Buffett" }
  ]
};
